# Manipulate Arrays Module

In [1]:
import numpy as np

## Views and Copies

In [2]:
array_one = np.array([-45, -60, 5, 6, 7, 8])
array_two = array_one

### Same or Different

In [3]:
array_one is array_two

True

In [4]:
id(array_one)

4373632224

In [5]:
id(array_two)

4373632224

### Value Equality

In [6]:
array_one == array_two

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [7]:
array_two[4] = 455

In [8]:
array_two[4]

455

In [9]:
array_one

array([-45, -60,   5,   6, 455,   8])

In [10]:
tree_house = np.array([-45, -60, 5, 6, 7, 8])
tree_house == array_two

array([ True,  True,  True,  True, False,  True], dtype=bool)

In [11]:
id(array_two)


4373632224

In [13]:
id(tree_house)

4373722016

In [14]:
tree_house is array_one

False