# Manipulate Arrays Module

In [16]:
import numpy as np

## Views and Copies

In [17]:
array_one = np.array([-45, -60, 5, 6, 7, 8])
array_two = array_one

### Same or Different

In [18]:
array_one is array_two

True

In [19]:
id(array_one)

4407717600

In [20]:
id(array_two)

4407717600

### Value Equality

In [21]:
array_one == array_two

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [22]:
array_two[4] = 455

In [23]:
array_two[4]

455

In [24]:
array_one

array([-45, -60,   5,   6, 455,   8])

In [25]:
tree_house = np.array([-45, -60, 5, 6, 7, 8])
tree_house == array_two

array([ True,  True,  True,  True, False,  True], dtype=bool)

In [26]:
id(array_two)


4407717600

In [27]:
id(tree_house)

4407796800

In [28]:
tree_house is array_one

False

# View :: A shallow copy

In [33]:
farm_house = tree_house.view()
farm_house.shape = (2, 3)

In [34]:
tree_house

array([-45, -60,   5,   6,   7,   8])

In [35]:
farm_house

array([[-45, -60,   5],
       [  6,   7,   8]])

# Deep Copy

In [36]:
dog_house = np.copy(tree_house)
dog_house[0] = -111
dog_house

array([-111,  -60,    5,    6,    7,    8])

In [37]:
tree_house

array([-45, -60,   5,   6,   7,   8])

# Array Attributes

In [40]:
a = np.array(np.arange(24)).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
# Number of Dimensions
a.ndim

3

In [42]:
a.shape

(2, 3, 4)

In [43]:
a.size

24

In [44]:
a.dtype

dtype('int64')

In [45]:
a.itemsize

8

In [46]:
type(a)

numpy.ndarray

# Adding and Removing Elements

In [47]:
a = np.array(np.arange(24)).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
b = np.append(a, [5, 6, 7, 8])

In [49]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [50]:
b.shape

(28,)

In [51]:
b.reshape(7, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [52]:
c = np.array(np.arange(24)).reshape(2, 3, 4) * 10 +3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [54]:
np.append(a, c, axis = 0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [55]:
np.append(a, c, axis = 0).shape

(4, 3, 4)

In [56]:
np.append(a, c, axis = 1).shape

(2, 6, 4)

In [57]:
np.append(a, c, axis = 1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [58]:
np.append(a, c, axis = 2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [59]:
np.append(a, c, axis = 2).shape

(2, 3, 8)

# Hay Stack

In [60]:
my_hay_stack = np.hstack((a, c))

In [61]:
my_hay_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [62]:
my_hay_stack[0, 0, 2] = 999

In [63]:
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [64]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [66]:
after_insert_array = np.insert(c, 1, 444, axis = 0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [67]:
after_insert_array = np.insert(c, 1, 444, axis = 1)

In [68]:
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [69]:
after_insert_array = np.insert(c, 1, 444, axis = 2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [71]:
d = np.empty(c.shape)
np.copyto(d, c)
d

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 163.,  173.,  183.,  193.],
        [ 203.,  213.,  223.,  233.]]])

In [72]:
np.delete(d, 1, axis = 0)

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]]])

In [73]:
np.delete(d, 1, axis = 1)

array([[[   3.,   13.,   23.,   33.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 203.,  213.,  223.,  233.]]])

In [74]:
np.delete(d, 1, axis = 2)

array([[[   3.,   23.,   33.],
        [  43.,   63.,   73.],
        [  83.,  103.,  113.]],

       [[ 123.,  143.,  153.],
        [ 163.,  183.,  193.],
        [ 203.,  223.,  233.]]])