# Manipulate Arrays Module

In [258]:
import numpy as np

## Views and Copies

In [259]:
array_one = np.array([-45, -60, 5, 6, 7, 8])
array_two = array_one

### Same or Different

In [260]:
array_one is array_two

True

In [261]:
id(array_one)

4507020304

In [262]:
id(array_two)

4507020304

### Value Equality

In [263]:
array_one == array_two

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [264]:
array_two[4] = 455

In [265]:
array_two[4]

455

In [266]:
array_one

array([-45, -60,   5,   6, 455,   8])

In [267]:
tree_house = np.array([-45, -60, 5, 6, 7, 8])
tree_house == array_two

array([ True,  True,  True,  True, False,  True], dtype=bool)

In [268]:
id(array_two)


4507020304

In [269]:
id(tree_house)

4507083760

In [270]:
tree_house is array_one

False

# View :: A shallow copy

In [271]:
farm_house = tree_house.view()
farm_house.shape = (2, 3)

In [272]:
tree_house

array([-45, -60,   5,   6,   7,   8])

In [273]:
farm_house

array([[-45, -60,   5],
       [  6,   7,   8]])

# Deep Copy

In [274]:
dog_house = np.copy(tree_house)
dog_house[0] = -111
dog_house

array([-111,  -60,    5,    6,    7,    8])

In [275]:
tree_house

array([-45, -60,   5,   6,   7,   8])

# Array Attributes

In [276]:
a = np.array(np.arange(24)).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [277]:
# Number of Dimensions
a.ndim

3

In [278]:
a.shape

(2, 3, 4)

In [279]:
a.size

24

In [280]:
a.dtype

dtype('int64')

In [281]:
a.itemsize

8

In [282]:
type(a)

numpy.ndarray

# Adding and Removing Elements

In [283]:
a = np.array(np.arange(24)).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [284]:
b = np.append(a, [5, 6, 7, 8])

In [285]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [286]:
b.shape

(28,)

In [287]:
b.reshape(7, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [288]:
c = np.array(np.arange(24)).reshape(2, 3, 4) * 10 +3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [289]:
np.append(a, c, axis = 0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [290]:
np.append(a, c, axis = 0).shape

(4, 3, 4)

In [291]:
np.append(a, c, axis = 1).shape

(2, 6, 4)

In [292]:
np.append(a, c, axis = 1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [293]:
np.append(a, c, axis = 2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [294]:
np.append(a, c, axis = 2).shape

(2, 3, 8)

# Hay Stack

In [295]:
my_hay_stack = np.hstack((a, c))

In [296]:
my_hay_stack

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [297]:
my_hay_stack[0, 0, 2] = 999

In [298]:
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [299]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [300]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [301]:
after_insert_array = np.insert(c, 1, 444, axis = 0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [302]:
after_insert_array = np.insert(c, 1, 444, axis = 1)

In [303]:
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [304]:
after_insert_array = np.insert(c, 1, 444, axis = 2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [305]:
d = np.empty(c.shape)
np.copyto(d, c)
d

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 163.,  173.,  183.,  193.],
        [ 203.,  213.,  223.,  233.]]])

In [306]:
np.delete(d, 1, axis = 0)

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]]])

In [307]:
np.delete(d, 1, axis = 1)

array([[[   3.,   13.,   23.,   33.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 203.,  213.,  223.,  233.]]])

In [308]:
np.delete(d, 1, axis = 2)

array([[[   3.,   23.,   33.],
        [  43.,   63.,   73.],
        [  83.,  103.,  113.]],

       [[ 123.,  143.,  153.],
        [ 163.,  183.,  193.],
        [ 203.,  223.,  233.]]])

# Join and Split Arrays

1. Concatenate
2. Stack
3. Split

In [309]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [310]:
a

array([[1, 2],
       [3, 4]])

In [311]:
b

array([[5, 6]])

In [312]:
together = np.concatenate((a, b), axis = 0)

In [313]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [314]:
together.shape

(3, 2)

In [315]:
together[1, 1] = 555

In [316]:
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [317]:
a

array([[1, 2],
       [3, 4]])

In [318]:
b

array([[5, 6]])

In [319]:
arrays = np.zeros((5, 3, 4))

for n in range(5):
    arrays[n] = np.random.randn(3,4)

arrays

array([[[ 0.94458502, -0.75792492,  0.56866143,  1.36721033],
        [-0.40813779,  0.87855491,  1.05035005, -1.4240724 ],
        [-0.36970038,  0.03809819,  0.40157241, -0.92028668]],

       [[-3.18546562, -0.26858642,  2.23776237, -1.02712367],
        [ 1.97487122, -0.78722317,  0.98524987,  0.71349652],
        [-0.59086071,  0.62469459, -0.97552746,  1.30046187]],

       [[ 0.10072   ,  0.49688057,  1.03354836,  0.78381798],
        [ 0.04193718, -0.41262395,  0.27993627,  0.16345723],
        [ 0.11254748, -1.56853196,  0.78294971,  0.17303386]],

       [[-0.39548193,  0.06867213, -1.74379418,  0.18469663],
        [-0.5067613 ,  0.58216959, -1.52114632,  0.83826375],
        [-0.91554207,  0.93133199,  0.54713099, -0.78231693]],

       [[-1.55576506, -0.64023313, -1.41762035, -1.66825315],
        [ 1.74701348,  0.04527108, -1.38348415, -1.89572381],
        [-0.78519183,  0.67723296, -0.18804514, -0.12491683]]])

In [320]:
stack0 = np.stack(arrays, axis = 0)
stack1 = np.stack(arrays, axis = 1)
stack2 = np.stack(arrays, axis = 2)

In [321]:
stack0

array([[[ 0.94458502, -0.75792492,  0.56866143,  1.36721033],
        [-0.40813779,  0.87855491,  1.05035005, -1.4240724 ],
        [-0.36970038,  0.03809819,  0.40157241, -0.92028668]],

       [[-3.18546562, -0.26858642,  2.23776237, -1.02712367],
        [ 1.97487122, -0.78722317,  0.98524987,  0.71349652],
        [-0.59086071,  0.62469459, -0.97552746,  1.30046187]],

       [[ 0.10072   ,  0.49688057,  1.03354836,  0.78381798],
        [ 0.04193718, -0.41262395,  0.27993627,  0.16345723],
        [ 0.11254748, -1.56853196,  0.78294971,  0.17303386]],

       [[-0.39548193,  0.06867213, -1.74379418,  0.18469663],
        [-0.5067613 ,  0.58216959, -1.52114632,  0.83826375],
        [-0.91554207,  0.93133199,  0.54713099, -0.78231693]],

       [[-1.55576506, -0.64023313, -1.41762035, -1.66825315],
        [ 1.74701348,  0.04527108, -1.38348415, -1.89572381],
        [-0.78519183,  0.67723296, -0.18804514, -0.12491683]]])

In [322]:
stack1

array([[[ 0.94458502, -0.75792492,  0.56866143,  1.36721033],
        [-3.18546562, -0.26858642,  2.23776237, -1.02712367],
        [ 0.10072   ,  0.49688057,  1.03354836,  0.78381798],
        [-0.39548193,  0.06867213, -1.74379418,  0.18469663],
        [-1.55576506, -0.64023313, -1.41762035, -1.66825315]],

       [[-0.40813779,  0.87855491,  1.05035005, -1.4240724 ],
        [ 1.97487122, -0.78722317,  0.98524987,  0.71349652],
        [ 0.04193718, -0.41262395,  0.27993627,  0.16345723],
        [-0.5067613 ,  0.58216959, -1.52114632,  0.83826375],
        [ 1.74701348,  0.04527108, -1.38348415, -1.89572381]],

       [[-0.36970038,  0.03809819,  0.40157241, -0.92028668],
        [-0.59086071,  0.62469459, -0.97552746,  1.30046187],
        [ 0.11254748, -1.56853196,  0.78294971,  0.17303386],
        [-0.91554207,  0.93133199,  0.54713099, -0.78231693],
        [-0.78519183,  0.67723296, -0.18804514, -0.12491683]]])

In [323]:
stack2

array([[[ 0.94458502, -3.18546562,  0.10072   , -0.39548193, -1.55576506],
        [-0.75792492, -0.26858642,  0.49688057,  0.06867213, -0.64023313],
        [ 0.56866143,  2.23776237,  1.03354836, -1.74379418, -1.41762035],
        [ 1.36721033, -1.02712367,  0.78381798,  0.18469663, -1.66825315]],

       [[-0.40813779,  1.97487122,  0.04193718, -0.5067613 ,  1.74701348],
        [ 0.87855491, -0.78722317, -0.41262395,  0.58216959,  0.04527108],
        [ 1.05035005,  0.98524987,  0.27993627, -1.52114632, -1.38348415],
        [-1.4240724 ,  0.71349652,  0.16345723,  0.83826375, -1.89572381]],

       [[-0.36970038, -0.59086071,  0.11254748, -0.91554207, -0.78519183],
        [ 0.03809819,  0.62469459, -1.56853196,  0.93133199,  0.67723296],
        [ 0.40157241, -0.97552746,  0.78294971,  0.54713099, -0.18804514],
        [-0.92028668,  1.30046187,  0.17303386, -0.78231693, -0.12491683]]])

In [324]:
s0 = np.split(stack0, 5, axis = 0)

In [325]:
s0

[array([[[ 0.94458502, -0.75792492,  0.56866143,  1.36721033],
         [-0.40813779,  0.87855491,  1.05035005, -1.4240724 ],
         [-0.36970038,  0.03809819,  0.40157241, -0.92028668]]]),
 array([[[-3.18546562, -0.26858642,  2.23776237, -1.02712367],
         [ 1.97487122, -0.78722317,  0.98524987,  0.71349652],
         [-0.59086071,  0.62469459, -0.97552746,  1.30046187]]]),
 array([[[ 0.10072   ,  0.49688057,  1.03354836,  0.78381798],
         [ 0.04193718, -0.41262395,  0.27993627,  0.16345723],
         [ 0.11254748, -1.56853196,  0.78294971,  0.17303386]]]),
 array([[[-0.39548193,  0.06867213, -1.74379418,  0.18469663],
         [-0.5067613 ,  0.58216959, -1.52114632,  0.83826375],
         [-0.91554207,  0.93133199,  0.54713099, -0.78231693]]]),
 array([[[-1.55576506, -0.64023313, -1.41762035, -1.66825315],
         [ 1.74701348,  0.04527108, -1.38348415, -1.89572381],
         [-0.78519183,  0.67723296, -0.18804514, -0.12491683]]])]

In [326]:
my_start_array = np.array(range(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [327]:
my_start_array.shape

(24,)

In [328]:
my_3_8_array = my_start_array.reshape((3,8))

In [329]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [330]:
my_3_8_array[0,0] = 2345

In [331]:
my_start_array

array([2345,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

# NumPy Ravel 

In [332]:
my_ravel_array = my_3_8_array.ravel()

In [333]:
my_ravel_array

array([2345,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

# NumPy Flat

In [334]:
for n in my_3_8_array.flat:
    print(n)

2345
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Rearranging Array Elements

In [335]:
my_start_array = np.array(np.arange((24)))
my_3_8_array = my_start_array.reshape((3, 8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

# fliplr "Flip Left Right"

In [336]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [337]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [338]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [339]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [340]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [341]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [342]:
np.roll(my_start_array, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [343]:
np.roll(my_start_array, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [344]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [345]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

# Transpose Like Operations

In [346]:
my_start_array = np.array(np.arange((24)))
my_3_8_array = my_start_array.reshape((3, 8))
my_2_3_4_array = my_start_array.reshape((2, 3, 4))

In [347]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [348]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [349]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [350]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

# Tiling Arrays

In [358]:
my_start_array = np.array(range(6))

In [359]:
my_start_array

array([0, 1, 2, 3, 4, 5])

In [360]:
tile1 = np.tile(my_start_array, 3)

In [363]:
tile1

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [364]:
tile2 = np.tile(my_start_array, (3, 1))

In [365]:
tile2

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

# Universal Functions
Functions that operate on NumPy arrays on element by element basis

In [366]:
def truncated_binomial(x):
    return (x+1)**3 - (x)**3

In [367]:
np.testing.assert_equal(truncated_binomial(4), 61)

In [369]:
my_numpy_function = np.frompyfunc(truncated_binomial, 1, 1)

In [370]:
my_numpy_function

<ufunc '? (vectorized)'>

In [371]:
test_array = np.arange(10)

In [372]:
my_numpy_function(test_array)

array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271], dtype=object)

In [373]:
big_test_array = np.outer(test_array, test_array)

In [374]:
big_test_array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [375]:
my_numpy_function(big_test_array)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 7, 19, 37, 61, 91, 127, 169, 217, 271],
       [1, 19, 61, 127, 217, 331, 469, 631, 817, 1027],
       [1, 37, 127, 271, 469, 721, 1027, 1387, 1801, 2269],
       [1, 61, 217, 469, 817, 1261, 1801, 2437, 3169, 3997],
       [1, 91, 331, 721, 1261, 1951, 2791, 3781, 4921, 6211],
       [1, 127, 469, 1027, 1801, 2791, 3997, 5419, 7057, 8911],
       [1, 169, 631, 1387, 2437, 3781, 5419, 7351, 9577, 12097],
       [1, 217, 817, 1801, 3169, 4921, 7057, 9577, 12481, 15769],
       [1, 271, 1027, 2269, 3997, 6211, 8911, 12097, 15769, 19927]], dtype=object)

# Pythagorean Triangles

In [376]:
def is_integer(x):
    return np.equal(np.mod(x, 1), 0)

In [377]:
numpy_is_integer = np.frompyfunc(is_integer, 1, 1)

In [378]:
number_of_triangles = 9
base = np.arange(number_of_triangles) + 1
height = np.arange(number_of_triangles) + 1

hypotenuse_squared = np.add.outer(base**2, height**2)
hypotenuse = np.sqrt(hypotenuse_squared)

In [379]:
numpy_is_integer(hypotenuse)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False, False],
       [False, False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, False],
       [False, False, False, False, False, False, False, False, False]], dtype=object)

# Linear Algebra

In [386]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9],[2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [387]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [388]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [389]:
my_first_matrix * my_first_matrix.I

matrix([[  1.00000000e+00,   1.11022302e-16,   0.00000000e+00],
        [ -1.38777878e-17,   1.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.11022302e-16,   1.00000000e+00]])

In [391]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [392]:
right_hand_side = np.matrix([[11], [22], [33]])
my_first_inverse = my_first_matrix.I

In [393]:
solution = my_first_inverse * right_hand_side

In [394]:
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

# Statistics

In [395]:
import scipy as sp
import matplotlib.pyplot as plt
from scipy.stats import norm

In [398]:
number_of_data_points = 10000
random_data_set = sp.randn(number_of_data_points)
type(random_data_set)

numpy.ndarray

In [399]:
random_data_set.mean()

-0.0017225007586883952

In [400]:
sp.median(random_data_set)

0.0039321654805898106

In [401]:
min_max = np.array([random_data_set.min(), random_data_set.max()])
min_max

array([-3.81240452,  3.77634715])

In [402]:
spread_measures = np.array([sp.std(random_data_set), sp.var(random_data_set)])
spread_measures

array([ 1.00348855,  1.00698928])

In [403]:
sp.stats.describe(random_data_set)

DescribeResult(nobs=10000, minmax=(-3.8124045223841172, 3.7763471470015362), mean=-0.0017225007586883952, variance=1.0070899875184456, skewness=0.01647994775215214, kurtosis=-0.02738287169982323)