# NumPy Arrays Notebook

## This is a notebook for prectising NumPy Arrays

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.13.1


In [4]:
my_list = list(range(1, 6, 1))

In [5]:
print(my_list)

[1, 2, 3, 4, 5]


In [6]:
array_from_list = np.array(my_list)

In [8]:
array_from_list

array([1, 2, 3, 4, 5])

In [9]:
array_from_list * 10

array([10, 20, 30, 40, 50])

In [11]:
my_tuple = (1, 3.14, 4+5j)
np.array(my_tuple)

array([ 1.00+0.j,  3.14+0.j,  4.00+5.j])

In [12]:
my_tuple * 6

(1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j))

In [13]:
np.array(my_tuple) * 6

array([  6.00 +0.j,  18.84 +0.j,  24.00+30.j])

# Intrinsic NumPy Arrays creation using NumPy Methods

In [14]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
np.arange(10, 50) - 10+ 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [18]:
len(np.arange(10, 25))

15

In [19]:
numpy_range_array = np.arange(10, 25)
numpy_range_array.size

15

In [20]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
np.arange(26, step = 4)

array([ 0,  4,  8, 12, 16, 20, 24])

# More NumPy Methods

In [22]:
np.linspace(5, 15, 9)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [28]:
np.linspace(0, 100, 10, retstep = True)

(array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
          44.44444444,   55.55555556,   66.66666667,   77.77777778,
          88.88888889,  100.        ]), 11.111111111111111)

# Zeros() Demo

In [31]:
np.zeros(20)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

# Ones() Demo

In [32]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
np.zeros((5, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [35]:
np.zeros((3, 4, 6))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]])

# Data Types Demo

In [36]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
np.ones(10, dtype = bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [39]:
np.ones(10, dtype = 'int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
np.ones(10, dtype = complex)

array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
        1.+0.j,  1.+0.j,  1.+0.j])

# Index Slice and Iterate

In [41]:
my_vector = np.array([-17, 5, 6, 7, 8, 9])

In [42]:
my_vector[4]

8

In [43]:
my_vector[4] = 144

In [44]:
my_vector[4]

144

In [45]:
my_vector[-3]

7

In [46]:
my_vector[305 % 6]

9

In [47]:
my_vector.size

6

In [48]:
my_vector[305 % my_vector.size]

9

In [49]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [50]:
my_array[3]

array([15, 16, 17, 18, 19])

In [51]:
my_array[-5]

array([10, 11, 12, 13, 14])

In [52]:
my_array[-4, -3]

17

## Three Dimensional Arrays

In [53]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [54]:
my_3d_array[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [55]:
my_3d_array[0,5]

array([25, 26, 27, 28, 29])

In [56]:
my_3d_array[0,5,3]

28

In [57]:
my_3d_array[1, 4, 4] = 5555

In [58]:
my_3d_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51,   52,   53,   54],
        [  55,   56,   57,   58, 5555],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

# Boolean Mask Arrays

In [59]:
my_vector = np.array([-6, 7, 4, 2, 4, 6])

In [60]:
my_vector

array([-6,  7,  4,  2,  4,  6])