# Boolean Mask Arrays

In [179]:
import numpy as np

In [180]:
my_vector = np.arange(8)
my_vector

array([0, 1, 2, 3, 4, 5, 6, 7])

In [181]:
zero_mod_7_mask = 0 == (my_vector % 7)

In [182]:
zero_mod_7_mask

array([ True, False, False, False, False, False, False,  True], dtype=bool)

In [183]:
sub_array = my_vector[zero_mod_7_mask]

In [184]:
sub_array

array([0, 7])

# NumPy Logical Operators

In [185]:
mod_test = 0 == (my_vector % 7)
mod_test

array([ True, False, False, False, False, False, False,  True], dtype=bool)

In [186]:
positive_test = my_vector > 0
positive_test

array([False,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [187]:
combined_mask = np.logical_and(mod_test, positive_test)

In [188]:
combined_mask

array([False, False, False, False, False, False, False,  True], dtype=bool)

In [189]:
my_vector[combined_mask]

array([7])

# Broadcasting

NumPy operations with arrays with different sizes

In [190]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [191]:
# Shape

my_3d_array.shape

(2, 7, 5)

In [192]:
# Number of Dimensions

my_3d_array.ndim

3

In [193]:
# Size

my_3d_array.size

70

In [194]:
# Data Type

my_3d_array.dtype

dtype('int32')

In [195]:
5*my_3d_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [196]:
left_mat = np.arange(6).reshape((2,3))
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [197]:
right_mat = np.arange(15).reshape((3,5))
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [198]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

# Operating Along Axes

In [199]:
my_3d_array.shape

(2, 7, 5)

In [200]:
my_3d_array.sum()

2415

In [201]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [202]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [203]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

# Broadcasting Rules

In [204]:
my_2d_array = np.ones(35, dtype = int).reshape((7,5)) * 3

In [205]:
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [206]:
my_random_2d_array = np.random.random((7, 5))

In [207]:
my_random_2d_array

array([[ 0.853 ,  0.9837,  0.8039,  0.8467,  0.7917],
       [ 0.6494,  0.4093,  0.2411,  0.5077,  0.4932],
       [ 0.256 ,  0.8658,  0.7702,  0.7939,  0.1354],
       [ 0.6767,  0.9681,  0.513 ,  0.8829,  0.2249],
       [ 0.8639,  0.6567,  0.3597,  0.845 ,  0.6644],
       [ 0.239 ,  0.0708,  0.9177,  0.8968,  0.1528],
       [ 0.2468,  0.8759,  0.5203,  0.3043,  0.2046]])

In [208]:
np.set_printoptions(precision = 4)
my_3d_array * my_random_2d_array

array([[[  0.    ,   0.9837,   1.6079,   2.5402,   3.167 ],
        [  3.2469,   2.4559,   1.6878,   4.0613,   4.4392],
        [  2.56  ,   9.5243,   9.2422,  10.3207,   1.8958],
        [ 10.15  ,  15.4889,   8.7204,  15.8929,   4.2735],
        [ 17.2771,  13.7905,   7.9135,  19.4343,  15.9463],
        [  5.9757,   1.8405,  24.7785,  25.1092,   4.4318],
        [  7.4032,  27.1522,  16.6494,  10.043 ,   6.9577]],

       [[ 29.8565,  35.4118,  29.746 ,  32.1755,  30.8778],
        [ 25.975 ,  16.782 ,  10.1268,  21.8296,  21.7028],
        [ 11.5199,  39.8287,  36.1987,  38.1074,   6.6353],
        [ 33.8335,  49.3709,  26.674 ,  46.7958,  12.1458],
        [ 47.5119,  36.7746,  20.5032,  49.0083,  39.2013],
        [ 14.3417,   4.3181,  56.8988,  56.4956,   9.7806],
        [ 16.0403,  57.8079,  34.8596,  20.6947,  14.1201]]])

In [209]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [210]:
my_3d_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [211]:
my_3d_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)

# Creating Structured Arrays

In [212]:
person_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [213]:
people_array = np.zeros(4, dtype = person_data_def)
people_array

array([(b'',  0.,  0., 0), (b'',  0.,  0., 0), (b'',  0.,  0., 0),
       (b'',  0.,  0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [214]:
people_array[3] = ('Delta', 73, 205, 34)

In [215]:
people_array[0] = ('Alpha', 65, 112, 23)

In [216]:
people_array

array([(b'Alpha',  65.,  112., 23), (b'',   0.,    0.,  0),
       (b'',   0.,    0.,  0), (b'Delta',  73.,  205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [217]:
people_array[0:]

array([(b'Alpha',  65.,  112., 23), (b'',   0.,    0.,  0),
       (b'',   0.,    0.,  0), (b'Delta',  73.,  205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [218]:
ages = people_array['age']

In [219]:
ages

array([23,  0,  0, 34], dtype=int64)

# Multi-Dimensional Structural Arrays

In [220]:
people_big_array = np.zeros((4,3,2), dtype = person_data_def)

In [221]:
people_big_array

array([[[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [222]:
people_big_array[3,2,1] = ('Echo', 67, 155, 46)

In [223]:
people_big_array

array([[[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'Echo',  67.,  155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [224]:
people_big_array['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,  67.]]])

In [225]:
people_big_array[['height', 'weight']]

array([[[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), ( 67.,  155.)]]],
      dtype=[('height', '<f8'), ('weight', '<f8')])

# Creating Record Array

In [226]:
person_record_array  = np.rec.array([('Donald', 78, 100, 34),('Knuth', 98, 102, 67)], dtype = person_data_def)
person_record_array

rec.array([(b'Donald',  78.,  100., 34), (b'Knuth',  98.,  102., 67)], 
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [227]:
person_record_array[0].age

34

In [228]:
person_record_array[0].height

78.0

In [229]:
person_record_array[0].weight

100.0

# Plots Matplotlib and PyPlot